const navWrap=document.querySelector('.nav-wrap');const progress=document.getElementById('progress');const menu=document.getElementById('menu');const navLinks=document.getElementById('navLinks');
window.addEventListener('scroll',()=>{navWrap.classList.toggle('scrolled',scrollY>20);const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/h*100)+'%';},{passive:true});
menu.addEventListener('click',()=>navLinks.classList.toggle('open'));navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target;const target=Number(el.dataset.count);let start=0;const duration=900;const t0=performance.now();const tick=now=>{const p=Math.min((now-t0)/duration,1);const eased=1-Math.pow(1-p,3);el.textContent=Math.round(target*eased);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);counterObserver.unobserve(el)}),{threshold:.8});document.querySelectorAll('[data-count]').forEach(el=>counterObserver.observe(el));
const projects={
 ixigo:{kicker:'PRODUCT CAPSTONE · IXIGO TRAINS',title:'Confident Alternatives',intro:'A product discovery and feature optimization case study focused on what happens when a traveller’s preferred train becomes unavailable. The work moved from research to prioritization, prototype, metrics and business impact.',stats:[['20','research interactions'],['15','opportunities prioritized'],['2','features designed'],['₹38.8 Cr','modelled annual impact']],sections:[['Problem framing','The starting question was why only 26% of users in the studied scenario resolved their booking within 24 hours after their preferred train became unavailable. Early assumptions were tested rather than treated as facts.'],['Research','Twenty research interactions surfaced a common underlying barrier appearing through two different user expressions. The insight changed the framing of the problem and guided the opportunity space.'],['Prioritization + solution','Fifteen opportunities were evaluated with RICE. Two features were selected and translated into product requirements, user flows and an interactive prototype with clearer confidence signals and transparent ranking.'],['Measurement + business impact','Defined a North Star metric and guardrail metrics, then modelled an estimated ₹38.8 crore incremental annual revenue opportunity to connect product impact with business outcomes.']],cta:'This case study is the centrepiece of my product portfolio: evidence → prioritization → solution → measurement.'},
 zomato:{kicker:'PRODUCT ANALYTICS · ZOMATO',title:'Retention & Funnel Analysis',intro:'A structured product analytics case study examining the food-delivery journey and the relationship between funnel movement and retention.',stats:[['8','funnel stages'],['AARRR','framework'],['Cohorts','analysis lens']],sections:[['Funnel','Mapped the end-to-end food-delivery journey into an 8-stage funnel to identify where user movement could be examined.'],['Cohorts','Used cohort analysis to reason about retention patterns rather than relying only on aggregate conversion.'],['Metrics','Connected the analysis to a North Star Metric and supporting metric ladder to make product outcomes measurable.']],cta:'Focus: turning product behavior into a metric system that teams can use to decide what to investigate next.'},
 x:{kicker:'PRODUCT STRATEGY · X',title:'Growth Roadmap',intro:'A product strategy case study that turns a broad set of growth opportunities into a structured roadmap using product epics and RICE prioritization.',stats:[['RICE','prioritization'],['Growth','epics'],['Roadmap','output']],sections:[['Opportunity space','Organized potential product expansion ideas into growth-oriented epics so that individual features could be evaluated in a strategic context.'],['Prioritization','Applied RICE to make the trade-offs between reach, impact, confidence and effort explicit.'],['Roadmap','Translated prioritized opportunities into a product roadmap that communicates sequencing rather than simply listing features.']],cta:'Focus: making strategy actionable through explicit prioritization and sequencing.'},
 vitafit:{kicker:'UX + PRODUCT REQUIREMENTS · VITAFIT',title:'Checkout Experience',intro:'A UX and product requirements case study focused on reducing friction in a checkout journey.',stats:[['Nielsen','heuristics'],['PRD','deliverable'],['UX','audit']],sections:[['Audit','Reviewed the checkout flow using Nielsen’s usability heuristics to identify usability issues and opportunities.'],['Problem translation','Converted UX findings into product problems rather than stopping at interface-level observations.'],['PRD','Structured requirements around the highest-value improvements, keeping the user journey and intended outcome at the centre.']],cta:'Focus: connecting qualitative UX evidence to product requirements.'},
 edtech:{kicker:'AI PRODUCT · EDTECH',title:'Recommendation System',intro:'A product design case study for a personalized EdTech recommendation experience balancing different learner personas, system requirements and privacy constraints.',stats:[['Multi-persona','design'],['NFRs','defined'],['Privacy','trade-off']],sections:[['Personas','Designed around multiple learner needs rather than assuming a single definition of relevance.'],['Requirements','Defined functional and non-functional requirements for a recommendation experience.'],['Trade-offs','Made personalization, recommendation quality and user privacy explicit as product constraints to be balanced.']],cta:'Focus: treating AI behavior as a product experience with requirements, constraints and measurable outcomes.'},
 ndn:{kicker:'M.TECH RESEARCH · TECHNICAL PRODUCT CONTEXT',title:'NDN Threat Detection',intro:'M.Tech research on detecting collusive and non-collusive Interest Flooding Attacks in Named Data Networking using Federated and Continual Learning.',stats:[['NDN','networking'],['FL','federated learning'],['CL','continual learning']],sections:[['Problem','Interest Flooding Attacks can degrade Named Data Networking by consuming network and forwarding resources. The research focuses on distinguishing collusive and non-collusive attack behavior.'],['Approach','The project explores distributed model training through federated learning and adaptation over time through continual learning.'],['Why it matters for product','It demonstrates the technical depth I bring to AI and network products: distributed systems, data, model behavior, drift and evaluation all become product constraints and opportunities.']],cta:'Focus: translating deep technical systems work into a product lens around reliability, detection, deployment and adaptation.'}
};
const modal=document.getElementById('modal');const modalContent=document.getElementById('modalContent');
function openProject(key){const p=projects[key];modalContent.innerHTML=`<div class="modal-kicker">${p.kicker}</div><h2>${p.title}</h2><p class="modal-intro">${p.intro}</p><div class="case-grid">${p.stats.map(s=>`<div class="case-box"><b>${s[0]}</b><span>${s[1]}</span></div>`).join('')}</div>${p.sections.map(s=>`<h4>${s[0]}</h4><p class="modal-intro">${s[1]}</p>`).join('')}<div class="modal-cta"><a class="btn primary" href="mailto:kvsortur@gmail.com?subject=${encodeURIComponent('Portfolio — '+p.title)}">Discuss this work ↗</a><button class="btn ghost" data-close>Close</button></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
document.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>openProject(card.dataset.project)));document.addEventListener('click',e=>{if(e.target.matches('[data-close]')){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open')){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}});document.getElementById('year').textContent=new Date().getFullYear();
