const navWrap=document.querySelector('.nav-wrap');const progress=document.getElementById('progress');const menu=document.getElementById('menu');const navLinks=document.getElementById('navLinks');
window.addEventListener('scroll',()=>{navWrap.classList.toggle('scrolled',scrollY>20);const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/Math.max(h,1)*100)+'%';},{passive:true});
menu.addEventListener('click',()=>navLinks.classList.toggle('open'));navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target;const target=Number(el.dataset.count);const duration=900;const t0=performance.now();const tick=now=>{const p=Math.min((now-t0)/duration,1);const eased=1-Math.pow(1-p,3);el.textContent=Math.round(target*eased);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);counterObserver.unobserve(el)}),{threshold:.8});document.querySelectorAll('[data-count]').forEach(el=>counterObserver.observe(el));
const projects={
ixigo:{kicker:'PRODUCT CAPSTONE · IXIGO TRAINS',title:'Confident Alternatives',intro:'A product discovery and feature optimization case study focused on what happens when a traveller’s preferred train becomes unavailable.',stats:[['20','research interactions'],['15','opportunities prioritized'],['2','features designed'],['₹38.8 Cr','modelled annual impact']],sections:[['Problem','Why do only 26% of users in the studied scenario resolve their booking within 24 hours after their preferred train becomes unavailable?'],['Research','Twenty research interactions surfaced one underlying barrier appearing through two different user expressions. The framing was revised around the evidence.'],['Prioritization + solution','Fifteen opportunities were RICE-scored; two were selected at 113.3 and 80.0. The solution used transparent High/Medium/Low confidence signals and clearer alternative ranking.'],['Prototype + measurement','The user flow was built as an interactive prototype in Lovable. A North Star metric, leading/lagging indicators and guardrails were defined.']],pdf:'case-studies/01_ixigo_confident_alternatives.pdf'},
zomato:{kicker:'PRODUCT ANALYTICS · ZOMATO',title:'Retention & Funnel Analysis',intro:'A structured product analytics case study examining the food-delivery journey and retention.',stats:[['8','funnel stages'],['AARRR','growth lens'],['Cohorts','retention lens'],['North Star','metric system']],sections:[['Funnel','Mapped an 8-stage food-delivery funnel to make user progression and drop-off points explicit.'],['Cohorts','Used cohort analysis to reason about retention patterns rather than relying only on aggregate averages.'],['Metrics','Proposed a North Star metric and supporting ladder metrics to connect behavior with product outcomes.']],pdf:'case-studies/02_zomato_retention.pdf'},
x:{kicker:'PRODUCT STRATEGY · X',title:'Growth Roadmap',intro:'A product strategy case study that turns a broad opportunity set into a prioritized roadmap.',stats:[['5','AARRR stages'],['5','growth epics'],['RICE','prioritization'],['Roadmap','output']],sections:[['Opportunity space','Mapped all five AARRR stages and organized product expansion ideas into growth epics.'],['Prioritization','Applied RICE to make reach, impact, confidence and effort explicit.'],['Roadmap','Sequenced the prioritized opportunities into a roadmap rather than a flat feature list.']],pdf:'case-studies/03_x_growth_roadmap.pdf'},
vitafit:{kicker:'UX + PRODUCT REQUIREMENTS · VITAFIT',title:'Checkout Experience',intro:'A UX and product requirements case study focused on reducing checkout friction.',stats:[['Nielsen','heuristics'],['UX','checkout audit'],['PRD','requirements'],['Conversion','business goal']],sections:[['Audit','Reviewed the checkout flow using Nielsen’s usability heuristics.'],['Problem translation','Converted usability findings into product problems and opportunities.'],['PRD','Structured requirements around the highest-value improvements and intended user outcome.']],pdf:'case-studies/04_vitafit_checkout.pdf'},
edtech:{kicker:'AI PRODUCT · EDTECH',title:'Recommendation System',intro:'A product design case study balancing personalization, learner personas, system requirements and privacy.',stats:[['Multi-persona','design'],['NFRs','defined'],['Privacy','trade-off'],['AI Product','focus']],sections:[['Personas','Designed around multiple learner needs rather than one definition of relevance.'],['Requirements','Defined functional and non-functional requirements for the recommendation experience.'],['Trade-offs','Made personalization quality and privacy explicit as constraints to balance.']],pdf:'case-studies/05_edtech_recommendation.pdf'},
ndn:{kicker:'M.TECH RESEARCH · TECHNICAL PRODUCT CONTEXT',title:'NDN Threat Detection',intro:'M.Tech research on detecting collusive and non-collusive Interest Flooding Attacks in Named Data Networking using Federated and Continual Learning.',stats:[['NDN','networking'],['FL','federated learning'],['CL','continual learning'],['ML','detection']],sections:[['Problem','Detect collusive and non-collusive Interest Flooding Attack behavior in a Named Data Networking environment.'],['Approach','Explore distributed training through federated learning and adaptation over time through continual learning.'],['Product relevance','Shows technical depth around reliability, model behavior, drift and deployment constraints in AI/network products.']],pdf:'case-studies/06_ndn_threat_detection.pdf'}};
const modal=document.getElementById('modal'),modalContent=document.getElementById('modalContent');
function openProject(key){const p=projects[key];modalContent.innerHTML=`<div class="modal-kicker">${p.kicker}</div><h2>${p.title}</h2><p class="modal-intro">${p.intro}</p><div class="case-grid">${p.stats.map(s=>`<div class="case-box"><b>${s[0]}</b><span>${s[1]}</span></div>`).join('')}</div>${p.sections.map(s=>`<h4>${s[0]}</h4><p class="modal-intro">${s[1]}</p>`).join('')}<div class="modal-cta"><a class="btn primary" href="${p.pdf}" target="_blank" rel="noreferrer">Open proof-of-work PDF ↗</a><a class="btn ghost" href="mailto:kvsortur@gmail.com?subject=${encodeURIComponent('Portfolio — '+p.title)}">Discuss this work ↗</a><button class="btn ghost" data-close>Close</button></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
document.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;openProject(card.dataset.project)}));
document.querySelectorAll('.proof-links button').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();openProject(btn.dataset.project)}));
document.addEventListener('click',e=>{if(e.target.matches('[data-close]')){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open')){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}});
document.getElementById('year').textContent=new Date().getFullYear();